Update ci-cd-backend.yml

diff --git a/.github/workflows/ci-cd-backend.yml b/.github/workflows/ci-cd-backend.yml
--- a/.github/workflows/ci-cd-backend.yml
+++ b/.github/workflows/ci-cd-backend.yml
@@ -80,19 +80,22 @@ jobs:
           SECRET_KEY: ${{ secrets.SECRET_KEY }}
           SERVICE_URL: ${{ secrets.SERVICE_URL }}
           EMAILADMIN: ${{ secrets.EMAILADMIN }}
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          EC2_IP: ${{ secrets.EC2_IP }}
         run: |
-          ssh -o "StrictHostKeyChecking=no" ec2-user@${{ secrets.EC2_IP }} << 'EOF'
-            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+          ssh -o "StrictHostKeyChecking=no" ec2-user@$EC2_IP << 'EOF'
+            # Navigate to the directory where docker-compose.yml is located
+            cd /path/to/your/project
 
-            docker pull ${{ secrets.DOCKER_USERNAME }}/lms-backend:latest
+            docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_PASSWORD }}
 
-            docker stop lms-backend-container || true
-            docker rm lms-backend-container || true
+            docker pull $DOCKER_USERNAME/lms-backend:latest
 
-            docker run -d -p 80:80 --name lms-backend-container \
-              -e ACCESS_KEY=${{ secrets.ACCESS_KEY }} \
-              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
-              -e SERVICE_URL=${{ secrets.SERVICE_URL }} \
-              -e EMAILADMIN=${{ secrets.EMAILADMIN }} \
-              ${{ secrets.DOCKER_USERNAME }}/lms-backend:latest
+            if ! command -v docker-compose &> /dev/null; then
+              echo "docker-compose not found. Installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '\"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            fi
+            docker-compose down || true
+            docker-compose up -d
           EOF
